"""
Model Loader — Placeholder for Compiled Model Integration
=========================================================
Provides functions to load the compiled model (generated by m2cgen in
Phase 3/4) and the decision threshold.

The compiled model is expected at:
  models/compiled_model.py  (Python source generated by m2cgen)

The decision threshold is expected at:
  models/threshold.txt      (single float, one per line)

Until Phase 3/4 produces the compiled model, these functions return
None and log a warning so the service can start in a degraded mode.

Usage:
    from serving.model_loader import load_model, get_feature_names, get_threshold

    model = load_model()
    features = get_feature_names()
    threshold = get_threshold()
"""

import importlib.util
import logging
import os

logger = logging.getLogger(__name__)

# Expected file paths (relative to project root)
_MODELS_DIR = os.path.join(os.path.dirname(__file__), "..", "models")
_COMPILED_MODEL_PATH = os.path.join(_MODELS_DIR, "compiled_model.py")
_THRESHOLD_PATH = os.path.join(_MODELS_DIR, "threshold.txt")

# Feature names expected by the model — must match the columns used
# during Phase 3/4 training.
_FEATURE_NAMES = [
    "reimbursement_zscore",
    "los_zscore",
    "visit_frequency_zscore",
    "code_severity_percentile",
    "high_severity_code_pct",
    "code_severity_outlier",
]

# Default threshold used when models/threshold.txt is absent
_DEFAULT_THRESHOLD = 0.5


def load_model():
    """Dynamically import and return the compiled model from models/compiled_model.py.

    The m2cgen-generated file typically exposes a ``predict`` callable at
    module level.  We import the module and return its ``predict`` attribute.

    Returns:
        callable with signature predict(features: list[float]) -> float,
        or None if the model file has not been compiled yet.
    """
    if not os.path.isfile(_COMPILED_MODEL_PATH):
        logger.warning(
            "Compiled model not found at %s. "
            "The scoring endpoint will return dummy scores. "
            "Run Phase 3/4 to compile the model.",
            _COMPILED_MODEL_PATH,
        )
        return None

    try:
        spec = importlib.util.spec_from_file_location("compiled_model", _COMPILED_MODEL_PATH)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        # m2cgen generates a module-level ``predict`` function
        if hasattr(module, "predict"):
            logger.info("Compiled model loaded from %s", _COMPILED_MODEL_PATH)
            return module.predict
        else:
            logger.error(
                "compiled_model.py does not expose a 'predict' callable. "
                "Check m2cgen output."
            )
            return None
    except Exception as exc:
        logger.error("Failed to load compiled model: %s", exc)
        return None


def get_feature_names():
    """Return the ordered list of feature names expected by the model.

    Returns:
        list[str]: feature column names in the order the model expects.
    """
    return list(_FEATURE_NAMES)


def get_threshold():
    """Load the decision threshold from models/threshold.txt.

    The file should contain a single float value (optionally with a
    trailing newline).  If the file is missing or unreadable, returns
    the default threshold of 0.5.

    Returns:
        float: the decision threshold for flagging claims.
    """
    if not os.path.isfile(_THRESHOLD_PATH):
        logger.warning(
            "Threshold file not found at %s. Using default threshold %.4f.",
            _THRESHOLD_PATH, _DEFAULT_THRESHOLD,
        )
        return _DEFAULT_THRESHOLD

    try:
        with open(_THRESHOLD_PATH, "r") as f:
            value = float(f.read().strip())
        logger.info("Loaded threshold: %.4f from %s", value, _THRESHOLD_PATH)
        return value
    except (ValueError, IOError) as exc:
        logger.warning(
            "Failed to read threshold file (%s). Using default %.4f.",
            exc, _DEFAULT_THRESHOLD,
        )
        return _DEFAULT_THRESHOLD
