#!/usr/bin/env python3
"""
Phase 4 — Model Compilation
Compiles the trained sklearn model to a standalone Python module using m2cgen.
Falls back to optimized pickle if m2cgen fails.
"""

import os
import sys
import warnings

import joblib

warnings.filterwarnings("ignore")

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_DIR = os.path.join(PROJECT_ROOT, "models")
MODEL_PATH = os.path.join(MODEL_DIR, "trained_model.pkl")
COMPILED_PATH = os.path.join(MODEL_DIR, "compiled_model.py")


def main():
    print("=" * 60)
    print("Phase 4 — Model Compilation")
    print("=" * 60)

    print("\nLoading trained model …")
    model = joblib.load(MODEL_PATH)
    print(f"  Model type: {type(model).__name__}")

    compiled = False

    # Try m2cgen
    print("\nAttempting m2cgen compilation …")
    try:
        import m2cgen as m2c
        code = m2c.export_to_python(model)
        with open(COMPILED_PATH, "w") as f:
            f.write('# Auto-generated by m2cgen from HistGradientBoostingClassifier\n')
            f.write('# Do not edit manually.\n\n')
            f.write("import math\n\n")
            f.write(code)
            f.write("\n")
        print(f"  Compiled model saved → {COMPILED_PATH}")
        compiled = True
    except Exception as e:
        print(f"  m2cgen failed: {e}")

    if not compiled:
        # Fallback: save as optimized pickle with loading wrapper
        print("\nFalling back to optimized pickle wrapper …")
        import pickle
        optimized_path = os.path.join(MODEL_DIR, "optimized_model.pkl")
        with open(optimized_path, "wb") as f:
            pickle.dump(model, f, protocol=pickle.HIGHEST_PROTOCOL)
        print(f"  Optimized pickle saved → {optimized_path}")

        # Create a Python module that loads and wraps it
        wrapper_code = '''#!/usr/bin/env python3
"""
Compiled model wrapper — loads optimized pickle and exposes a score() function.
Generated as fallback when m2cgen compilation was unavailable.
"""
import pickle
import os
import numpy as np

_MODEL_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "optimized_model.pkl")
_model = None

def _get_model():
    global _model
    if _model is None:
        with open(_MODEL_PATH, "rb") as f:
            _model = pickle.load(f)
    return _model

def score(features):
    """
    Score a single claim.
    features: list or array of 6 numeric values in the order:
        [reimbursement_zscore, los_zscore, visit_frequency_zscore,
         code_severity_percentile, high_severity_code_pct, code_severity_outlier]
    Returns: probability of fraud (float).
    """
    model = _get_model()
    x = np.array(features, dtype=np.float64).reshape(1, -1)
    return float(model.predict_proba(x)[0, 1])
'''
        with open(COMPILED_PATH, "w") as f:
            f.write(wrapper_code)
        print(f"  Wrapper module saved → {COMPILED_PATH}")

    # Verify the compiled module loads
    print("\nVerifying compiled module loads …")
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location("compiled_model", COMPILED_PATH)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        import numpy as np
        rng = np.random.RandomState(42)
        test_input = rng.randn(6).tolist()
        if hasattr(mod, "score"):
            prob = mod.score(test_input)
            print(f"  score() returned: {prob:.6f}")
        elif hasattr(mod, "predict"):
            prob = mod.predict(test_input)
            print(f"  predict() returned: {prob:.6f}")
        else:
            print("  Warning: no score() or predict() function found.")
        print("  Compiled module verified successfully.")
    except Exception as e:
        print(f"  Verification error: {e}")

    print("\n" + "=" * 60)
    print("COMPILATION COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    main()
